version: '3'

services:
  todoapp:
    image: postgres
    container_name: database_todoapp
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todoapp
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: todoapp
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - todoapp
    depends_on:
      - todoapp

volumes:
  pgdata:
    driver: local
